__version__ = "1.0.10"
__authors__: list[str] = [
    "Lukas Frank <lukasf@unis.no",
    "Jakob Dörr <jakob.dorr@uib.no",
    "Patrick Selle <patrick.selle@uni-potsdam.de",
]

from .Meteo import (
    read_MET_AWS,
    read_Campbell_TOA5,
    read_EddyPro_full_output,
    read_Tinytag,
    read_HOBO,
    read_Raingauge,
    read_IWIN,
    read_AROME,
    read_radiosonde,
    read_iMet,
    download_IWIN_from_THREDDS,
    MapGenerator,
)

from .Ocean import (
    cal_dist_dir_on_sphere,
    cart2pol,
    pol2cart,
    create_latlon_text,
    CTD_to_grid,
    CTD_to_xarray,
    section_to_xarray,
    mooring_to_xarray,
    calc_freshwater_content,
    myloadmat,
    mat2py_time,
    ctd_identify_water_masses,
    read_ADCP_CODAS,
    split_CODAS_resolution,
    read_WinADCP,
    read_LADCP,
    read_CTD,
    read_CTD_from_mat,
    read_MSS,
    read_mooring,
    read_Seaguard,
    read_Minilog,
    read_SBE37,
    read_RBR,
    read_Thermosalinograph,
    download_tidal_model,
    detide_VMADCP,
    tide,
    calculate_tidal_spectrum,
    tidal_harmonic_analysis,
    contour_section,
    plot_CTD_section,
    plot_CTD_single_section,
    plot_xarray_sections,
    plot_CTD_station,
    plot_CTD_map,
    plot_empty_map,
    plot_CTD_ts,
    create_empty_ts,
    check_VM_ADCP_map,
    plot_tidal_spectrum,
    plot_map_tidal_ellipses,
    portasal,
    play_tone,
)

from .MET_model_download import (
    download_MET_model_data,
    download_MET_model_static_fields,
    MET_model_download_class,
)

from .universal_func import std_names, progress_bar, present_dict
